vpc_name    = "orient"
vpc_cidr    = "172.16.0.0/16"
env         = "production"
IGW_name    = "orient-IGW"
public_subnet1_name = "orient-public-subnet1"
public_subnet1_cidr = "172.16.20.0/24"
Public_Routing_Table_name = "orientPRTB"
